# 生产环境配置
# 作者: Sakura Huang
# 创建时间: 2025-09-03

spring:
  # 数据源配置（生产环境）
  datasource:
    url: jdbc:mysql://localhost:3306/poetry_app_dev?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: ${DB_USERNAME:poetry_user}
    password: ${DB_PASSWORD:your_production_password}
    
    # Druid连接池配置（生产环境）
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      
      # 关闭监控（生产环境）
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
        
  # Redis配置（生产环境）
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:your_redis_password}
      database: 0
      
      # Redis集群配置（如需要）
      # cluster:
      #   nodes: 
      #     - 192.168.1.100:7000
      #     - 192.168.1.100:7001
      #     - 192.168.1.100:7002

# 服务器配置（生产环境）
server:
  port: ${SERVER_PORT:8080}
  # 启用压缩
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  # HTTP/2支持
  http2:
    enabled: true

# MyBatis-Plus配置（生产环境）
mybatis-plus:
  configuration:
    # 关闭SQL日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 日志配置（生产环境）
logging:
  level:
    root: warn
    com.sakura.poetry: info
    com.sakura.poetry.mapper: warn
  file:
    name: /var/log/poetry-app/the-poetry-app-server.log
    max-size: 100MB
    max-history: 30

# 应用配置（生产环境）
app:
  # 生产模式
  debug: false
  
  # JWT配置（生产环境使用环境变量）
  jwt:
    secret: ${JWT_SECRET:your_production_jwt_secret_key}
    
  # 文件存储配置
  file:
    upload-path: ${FILE_UPLOAD_PATH:/opt/poetry-app/uploads/}
    
  # 跨域配置（生产环境限制域名）
  cors:
    enabled: true
    allowed-origins: 
      - ${ALLOWED_ORIGIN_1:https://poetry.example.com}
      - ${ALLOWED_ORIGIN_2:https://admin.poetry.example.com}

# 管理端点配置（生产环境）
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never